<a href="https://colab.research.google.com/github/recognai/bds-nlp-2018/blob/master/pytorch_1_0_0_gpu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'
!pip install torch_nightly -f https://download.pytorch.org/whl/nightly/{accelerator}/torch_nightly.html
  
import torch

Looking in links: https://download.pytorch.org/whl/nightly/cu92/torch_nightly.html
    100% |████████████████████████████████| 589.3MB 28kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x622f4000 @  0x7f27a393f2a4 0x594e17 0x626104 0x51190a 0x4f5277 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x4f3338 0x510fb0 0x5119bd 0x4f6070


In [2]:
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.backends.cudnn.enabled)

1.0.0.dev20181108
True
True


# Tensors

The main data structure for computing things in Pytorch are tensors.

Let's create some tensors with different shapes.

In [20]:
# Vector 1D 3
data = [1., 2., 3.]
v = torch.tensor(data)
v

tensor([1., 2., 3.])

In [22]:
# Tensors have a shape, this is our vector shape
v.shape

torch.Size([3])

In [7]:
# Matrix 2D 2x3
m_data = [data, data]
m = torch.tensor(m_data)
m

tensor([[1., 2., 3.],
        [1., 2., 3.]])

In [8]:
# Matrix shape
m.shape

torch.Size([2, 3])

In [13]:
# Tensor 3D 2x2x3
t_data = [[data, data], [data, data]]
t = torch.tensor(t_data)
t

tensor([[[1., 2., 3.],
         [1., 2., 3.]],

        [[1., 2., 3.],
         [1., 2., 3.]]])

In [14]:
t.shape

torch.Size([2, 2, 3])

In [17]:
# Indexing into vectors gives you a scalar
v[0]

tensor(1.)

In [18]:
# Indexing into matrices gives you a vector
m[0]

tensor([1., 2., 3.])

In [19]:
# Indexing into 3D tensors gives you a matrix
t[0]

tensor([[1., 2., 3.],
        [1., 2., 3.]])

# Some operations with tensors

Here we see only some examples, you can check the extensive guide in pytorch's [documentation](https://pytorch.org/docs/stable/torch.html)

In [32]:
x = torch.tensor(data)
y = torch.tensor([2., 3., 4.])
x + y

tensor([3., 5., 7.])

In [33]:
x*y

tensor([ 2.,  6., 12.])

In [34]:
x.dot(y)

tensor(20.)

In [41]:
# Concatenation along first axis (rows)
x_1 = torch.randn(2, 5)
print(x_1)
y_1 = torch.rand(3, 5)
print(y_1)
z_1 = torch.cat([x_1, y_1])
z_1


tensor([[ 0.2002,  0.3149, -0.8152, -0.4174, -0.3474],
        [ 1.1388, -1.7068, -2.3700,  1.3907,  0.2357]])
tensor([[0.3692, 0.3334, 0.5936, 0.2308, 0.8848],
        [0.0731, 0.4664, 0.4622, 0.7756, 0.1131],
        [0.1097, 0.4125, 0.9174, 0.4316, 0.2276]])


tensor([[ 0.2002,  0.3149, -0.8152, -0.4174, -0.3474],
        [ 1.1388, -1.7068, -2.3700,  1.3907,  0.2357],
        [ 0.3692,  0.3334,  0.5936,  0.2308,  0.8848],
        [ 0.0731,  0.4664,  0.4622,  0.7756,  0.1131],
        [ 0.1097,  0.4125,  0.9174,  0.4316,  0.2276]])

In [43]:
# Concatenation along second axis (cols)
x_2 = torch.randn(2, 3)
print(x_2)
y_2 = torch.rand(2, 5)
print(y_2)
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)
z_2.shape


tensor([[-0.5795,  1.1239,  1.7605],
        [-0.2429, -1.0143,  0.3247]])
tensor([[0.4940, 0.8373, 0.7835, 0.2938, 0.0788],
        [0.0974, 0.2213, 0.4784, 0.4499, 0.6529]])
tensor([[-0.5795,  1.1239,  1.7605,  0.4940,  0.8373,  0.7835,  0.2938,  0.0788],
        [-0.2429, -1.0143,  0.3247,  0.0974,  0.2213,  0.4784,  0.4499,  0.6529]])


torch.Size([2, 8])

In [0]:
# Incompatible concat: try uncommenting
# torch.cat([x_1, x_2])

# Reshaping tensors
This is a widely used operation in order to feed the different neural network components with the right input shapes. We will see some concrete examples later.


In [68]:
x = torch.randn(2,2,2)
print(x)
x.shape


tensor([[[ 0.9308, -1.0904],
         [-0.8758, -1.0550]],

        [[-0.2316,  0.0204],
         [-0.3667, -0.8472]]])


torch.Size([2, 2, 2])

In [74]:
# Reshape into a matrix of 2 rows 4 columns
print(x.view(2, 4))

tensor([[ 0.9308, -1.0904, -0.8758, -1.0550],
        [-0.2316,  0.0204, -0.3667, -0.8472]])


In [87]:
# You can use -1 for letting torch inferring the size of one of the dimensions
print(x.view(-1,4))
# print(x.view(2, -1), x.view(2, -1).shape)
# print(x.view(-1, 8), x.view(-1, 8).shape)
# print(x.view(1, -1), x.view(1, -1).shape)
# print(x.view(4, -1), x.view(4, -1).shape)

tensor([[ 0.9308, -1.0904, -0.8758, -1.0550],
        [-0.2316,  0.0204, -0.3667, -0.8472]])
